language: haxe
haxe:
  - development

install:
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime
  - haxelib install openfl
  - haxelib install hscript
  - haxelib install flixel
  
script:
    
  - haxelib run lime build haxe/exampleFlixel neko -Dlegacy
  # swf 11 because of Travis CI:
  # /home/travis/haxelib/flixel/3,3,11/flixel/input/gamepad/FlxGamepadManager.hx:257: characters 33-60 : Accessing this field requires flash version 11.8 (use -swf-version 11.8)
  - haxelib run lime build haxe/exampleFlixel flash -Dlegacy -swf-version 11.8
  - haxelib run lime build haxe/exampleOpenFL neko -Dlegacy
  - haxelib run lime build haxe/exampleOpenFL flash -Dlegacy
  
cache:
  directories:
    - ~/haxelib