language: haxe
haxe:
  - development

install:
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime
  - haxelib install openfl
  - haxelib install hscript
  - haxelib install flixel
  
script:
  - haxelib run lime build haxe/exampleFlixel neko -Dlegacy
  - haxelib run lime build haxe/exampleFlixel flash -Dlegacy
  - haxelib run lime build haxe/exampleOpenFL neko -Dlegacy
  - haxelib run lime build haxe/exampleOpenFL flash -Dlegacy
  
cache:
  directories:
    - ~/haxelib